spring:
  config:
    activate:
      on-profile: test

  liquibase:
    enabled: true
    contexts: test

  datasource:
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    open-in-view: false
    show-sql: true


logging:
  level:
    de.marshal: debug

bank:
  client-id: -1
  account-ids:
    978: -1
    840: -2
  default-product-ids:
    978: -1
    840: -2

jwt:
  secret: ssqUi2G0KTbTx8aqzhVn4p3+xVGhy5vWDhL7m8kpkTmqZRFgh53kmks28STubJm9FmwtDmV0QuEoJ9whZKx6HA==
  test:
    auth-token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJCYW5rIHN1YnN5c3RlbSIsImV4cCI6OTIyMzM3MjAzNjg1NDc3NX0.-uDOUYe6kl6UQYsJzgJEoMjydPPj_cJ2H-kXb95JmqFv0pc6Hrrz8laVmCn6gMutUl4cmwxW0JCQpGh3ucoFdA

---

server:
  shutdown: graceful
  servlet:
    context-path: /
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  config:
    activate:
      on-profile: default

  main:
    banner-mode: off

  liquibase:
    enabled: true

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # https://www.baeldung.com/spring-boot-properties-env-variables
    url: "${JDBC_URL}"
    username: "${JDBC_USERNAME}"
    password: "${JDBC_PASSWORD}"

    hikari:
      pool-name: BankApp
      register-mbeans: true
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
      max-lifetime: 2000000
      idle-timeout: 30000
  jpa:
    #    generate-ddl: false
    #    hibernate:
    #      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG

bank:
  client-id: -1
  account-ids:
    978: -1
    840: -2
  default-product-ids:
    978: -1
    840: -2

jwt:
  secret: "${JWT_SECRET}"
